spring:
  application:
    name: rental-backend

  datasource:

    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rentals?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:

  secret: ${JWT_SECRET:dev-please-change-me-0123456789-abcdefghijklmnopqrstuvwxyz}
  expirationMinutes: ${JWT_EXP_MIN:120}

server:
  port: ${SERVER_PORT:8080}


springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui/index.html

logging:
  level:
    org.springframework.security: info
    org.hibernate.SQL: warn
